version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  robotreport:
    image: ${DOCKER_REGISTRY-}robotreport
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+:80
      - DB_CONNECTION_STRING:host=postgres;port=5432;database=robotdb;username=root;password=root

    networks:
      - dockerapi-dev
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5050:5432"
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "robotdb"
    #  PGDATA: "/data/postgres"
    networks:
      - dockerapi-dev

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5051:80"
    networks:
      - dockerapi-dev

volumes:
  db_volume:
         
    
     
