version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  robotreport:
    image: ${DOCKER_REGISTRY-}robotreport
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgres_image"
    ports:
      - "5000:5000"     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5000;http://+:80
      - DB_CONNECTION_STRING:host=postgres_image;port=5432;database=robotdb;username=robotuser;password=robotuser

    networks:
      - dockerapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5050:5432"
    restart: always
    #volumes:
    #  - db_volume:/var/lib/postgresql/data
    #  - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "robotuser"
      POSTGRES_PASSWORD: "robotuser"
      POSTGRES_DB: "robotdb"
    networks:
      - dockerapi-dev


volumes:
  db_volume:
         
    
     
